[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=54545): Read timed out. (read timeout=120)")': /session/3a6ad66667afdcd4b164772208913e18/screenshot