{"uuid": "c9dc62ee-122f-49f9-b72b-8de0889e76ac", "children": ["97d42b82-e9e1-4378-bd42-c3bc0b873db4"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1750169185701, "stop": 1750169185701}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x0x7ff63b2dfe75+79173]\n\tGetHandleVerifier [0x0x7ff63b2dfed0+79264]\n\t(No symbol) [0x0x7ff63b099c8c]\n\t(No symbol) [0x0x7ff63b0e05ef]\n\t(No symbol) [0x0x7ff63b118832]\n\t(No symbol) [0x0x7ff63b113233]\n\t(No symbol) [0x0x7ff63b1122f9]\n\t(No symbol) [0x0x7ff63b065fc5]\n\tGetHandleVerifier [0x0x7ff63b5aa2ad+3004797]\n\tGetHandleVerifier [0x0x7ff63b5a46fd+2981325]\n\tGetHandleVerifier [0x0x7ff63b5c3350+3107360]\n\tGetHandleVerifier [0x0x7ff63b2fa9fe+188622]\n\tGetHandleVerifier [0x0x7ff63b30228f+219487]\n\t(No symbol) [0x0x7ff63b065036]\n\tGetHandleVerifier [0x0x7ff63b6c3c48+4158232]\n\tBaseThreadInitThunk [0x0x7ffcdfade8d7+23]\n\tRtlUserThreadStart [0x0x7ffce1c1c34c+44]\n\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\Udmey\\Python-Workspace\\SalesforceAutomationPoc\\testcases\\conftest.py\", line 69, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"failed_test\",\n                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1019, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1029, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750169232330, "stop": 1750169232606}], "start": 1750169185701, "stop": 1750169232606}