{"uuid": "96ae39d6-669f-4b63-af00-7be499337e04", "children": ["a01cfd4e-ca4a-4344-881b-a0e6f76a949c"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1750167868843, "stop": 1750167868843}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\Udmey\\Python-Workspace\\SalesforceAutomationPoc\\testcases\\conftest.py\", line 56, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1750167868866, "stop": 1750167868869}], "start": 1750167868843, "stop": 1750167868869}