{"uuid": "263a03d4-6639-41d7-8b72-c3fc5872c783", "children": ["55e18718-091e-4090-998b-d9e837ad09b9"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1750169020599, "stop": 1750169020599}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\Udmey\\Python-Workspace\\SalesforceAutomationPoc\\testcases\\conftest.py\", line 53, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1750169020600, "stop": 1750169020601}], "start": 1750169020599, "stop": 1750169020601}