{"uuid": "bf92babb-8350-44f5-b3e0-781ae8594781", "children": ["841be21a-91fd-457e-ac1a-7c9bfac2f76e"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1750168854022, "stop": 1750168854022}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\Udmey\\Python-Workspace\\SalesforceAutomationPoc\\testcases\\conftest.py\", line 53, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1750168854026, "stop": 1750168854029}], "start": 1750168854022, "stop": 1750168854029}