{"uuid": "ebe54f23-0f8b-439d-aab9-f8b340dc553b", "children": ["302fde74-14a1-497e-b77f-1103f69d51ec"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1750010256946, "stop": 1750010256946}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x0x7ff606fbfe75+79173]\n\tGetHandleVerifier [0x0x7ff606fbfed0+79264]\n\t(No symbol) [0x0x7ff606d79c8c]\n\t(No symbol) [0x0x7ff606dc05ef]\n\t(No symbol) [0x0x7ff606df8832]\n\t(No symbol) [0x0x7ff606df3233]\n\t(No symbol) [0x0x7ff606df22f9]\n\t(No symbol) [0x0x7ff606d45fc5]\n\tGetHandleVerifier [0x0x7ff60728a2ad+3004797]\n\tGetHandleVerifier [0x0x7ff6072846fd+2981325]\n\tGetHandleVerifier [0x0x7ff6072a3350+3107360]\n\tGetHandleVerifier [0x0x7ff606fda9fe+188622]\n\tGetHandleVerifier [0x0x7ff606fe228f+219487]\n\t(No symbol) [0x0x7ff606d45036]\n\tGetHandleVerifier [0x0x7ff6073a3c48+4158232]\n\tBaseThreadInitThunk [0x0x7ffcdfade8d7+23]\n\tRtlUserThreadStart [0x0x7ffce1c1c34c+44]\n\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\Udmey\\Python-Workspace\\SalesforceAutomationPoc\\testcases\\conftest.py\", line 53, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"failed_test\",\n                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1019, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1029, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750010365582, "stop": 1750010365700}], "start": 1750010256946, "stop": 1750010365700}