{"name": "test_loginsalesforce_validcredentials[test_list_item0]", "status": "broken", "statusDetails": {"message": "simple_salesforce.exceptions.SalesforceAuthenticationFailed: invalid_grant: authentication failure", "trace": "self = <testcases.login_test.TestLogin object at 0x000002565A469A90>, test_list_item = {'password': 'Pra245pte#', 'username': 'pgbitbucket706@agentforce.com'}\nrequest = <FixtureRequest for <Function test_loginsalesforce_validcredentials[test_list_item0]>>\n\n    @pytest.mark.smoke\n    @pytest.mark.parametrize(\"test_list_item\", BaseTest.get_data_from_json(Login_test_data_path,\"valid_login\"))\n    def test_loginsalesforce_validcredentials(self, test_list_item,request):\n        loginpage = LoginPage(self.driver)\n>       homepage = loginpage.logintosalesforce(test_list_item[\"username\"],test_list_item[\"password\"],request)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\ntestcases\\login_test.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\loginPage.py:23: in logintosalesforce\n    homepage = HomePage(self.driver,request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npages\\homePage.py:13: in __init__\n    self.sf_utils = SalesforceUtils(request)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^\nutility\\salesforce_data_utils.py:16: in __init__\n    self.sf = self.authenticate_salesforce()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nutility\\salesforce_data_utils.py:29: in authenticate_salesforce\n    sf = Salesforce(\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\simple_salesforce\\api.py:215: in __init__\n    self._refresh_session()\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\simple_salesforce\\api.py:307: in _refresh_session\n    self.session_id, self.sf_instance = self._salesforce_login_partial()\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\simple_salesforce\\login.py:127: in SalesforceLogin\n    return token_login(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ntoken_url = 'https://login.salesforce.com/services/oauth2/token'\ntoken_data = {'client_id': '3MVG9rZjd7MXFdLjZbuLuU2UtK9NYe4fuB27tdXI8TRtYz9Qdxm68_slvWM3WUkyt5frZrwR5Y3lZig82.HkA', 'client_secret'...41E000DDAC6BAA44FD590074138573737C169A902621431267C2FF1E32AB', 'grant_type': 'password', 'password': 'Pra245pte#', ...}\ndomain = 'login', consumer_key = '3MVG9rZjd7MXFdLjZbuLuU2UtK9NYe4fuB27tdXI8TRtYz9Qdxm68_slvWM3WUkyt5frZrwR5Y3lZig82.HkA', headers = None, proxies = {}\nsession = <requests.sessions.Session object at 0x000002565A4AD940>\n\n    def token_login(\n            token_url: str,\n            token_data: Dict[str, Any],\n            domain: str,\n            consumer_key: str,\n            headers: Optional[Headers],\n            proxies: Optional[Proxies],\n            session: Optional[requests.Session] = None) -> Tuple[Any, Any]:\n        \"\"\"Process OAuth 2.0 JWT Bearer Token Flow.\"\"\"\n        response = (session or requests).post(\n            token_url, token_data, headers=headers, proxies=proxies)\n    \n        try:\n            json_response = response.json()\n        except JSONDecodeError as exc:\n            raise SalesforceAuthenticationFailed(\n                response.status_code, response.text\n                ) from exc\n    \n        if response.status_code != 200:\n            except_code = json_response.get('error')\n            except_msg = json_response.get('error_description')\n            if except_msg == \"user hasn't approved this consumer\":\n                auth_url = f'https://{domain}.salesforce.com/services/oauth2/' \\\n                           'authorize?response_type=code&client_id=' \\\n                           f'{consumer_key}&redirect_uri=<approved URI>'\n                warnings.warn(f\"\"\"\n        If your connected app policy is set to \"All users may\n        self-authorize\", you may need to authorize this\n        application first. Browse to\n        {auth_url}\n        in order to Allow Access. Check first to ensure you have a valid\n        <approved URI>.\"\"\")\n>           raise SalesforceAuthenticationFailed(except_code, except_msg)\nE           simple_salesforce.exceptions.SalesforceAuthenticationFailed: invalid_grant: authentication failure\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\simple_salesforce\\login.py:310: SalesforceAuthenticationFailed"}, "attachments": [{"name": "stdout", "source": "3f45e331-c650-43c5-a91a-64cb29aa0365-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_list_item", "value": "{'username': 'pgbitbucket706@agentforce.com', 'password': 'Pra245pte#'}"}], "start": 1750353170158, "stop": 1750353177396, "uuid": "1c5cda94-eef3-4092-b5f9-e1a707b40764", "historyId": "4fa26c5d8a8f3f216283ca707f04bde8", "testCaseId": "edd327156eda62a83bae9df650959eeb", "fullName": "testcases.login_test.TestLogin#test_loginsalesforce_validcredentials", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-QPHGE425"}, {"name": "thread", "value": "23568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.login_test"}]}