{"uuid": "aba5bcbd-80f4-4008-9572-153a1f5efce6", "children": ["4ffb46a7-e24b-46a7-9d49-352cdeb54859"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1750347775795, "stop": 1750347775795}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\Udmey\\Python-Workspace\\SalesforceAutomationPoc\\testcases\\conftest.py\", line 65, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1750347779124, "stop": 1750347779129}], "start": 1750347775795, "stop": 1750347779129}