{"uuid": "d3c8fd6c-02fd-4097-a674-cd942fb1ae57", "children": ["eaf11792-7d6c-4ee8-aea8-634aaf3ace47"], "befores": [{"name": "authenticate_salesforce", "status": "broken", "statusDetails": {"message": "simple_salesforce.exceptions.SalesforceAuthenticationFailed: invalid_grant: authentication failure\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Udmey\\Python-Workspace\\SalesforceAutomationPoc\\testcases\\conftest.py\", line 54, in authenticate_salesforce\n    sf = Salesforce(instance_url=sf_url, username=sf_username,\n                    password=sf_password,consumer_key=sf_consumer_key,\n                    consumer_secret=sf_consumer_secret)\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\simple_salesforce\\api.py\", line 215, in __init__\n    self._refresh_session()\n    ~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\simple_salesforce\\api.py\", line 307, in _refresh_session\n    self.session_id, self.sf_instance = self._salesforce_login_partial()\n                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\simple_salesforce\\login.py\", line 127, in SalesforceLogin\n    return token_login(\n        f'https://{domain}.salesforce.com/services/oauth2/token',\n        token_data, domain, consumer_key,\n        None, proxies, session)\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\simple_salesforce\\login.py\", line 310, in token_login\n    raise SalesforceAuthenticationFailed(except_code, except_msg)\n"}, "start": 1750347715457, "stop": 1750347716022}], "start": 1750347715457, "stop": 1750347717298}